pipeline {
    agent any
    environment {
        registry = "siva546/merchant_galaxy"
        registryCredential = 'dockerhub'
    	}
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    echo "I am in build step"
                    chmod +x gradlew
                    ./gradlew build
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage ="
                    docker build -t mogimage:1.0 .
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Pubishing DockerImage ="
                    docker tag mogimage:1.0 siva546/merchant_galaxy
                    docker.withRegistry( '', registryCredential ) {
                        siva546/merchant_galaxy.push()
                    }
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
}
